### ISSUE TITLE
API responses don't include version information

### ISSUE THREAD

**Issue by jackdos** [openpreserve/par#20]
As a consumer of the API, I want to know what version of the API/Schema the endpoint is implementing, so that I know how to marshall the response and what further queries, filters, etc are possible.

**Comment by jackdos** [comment]
Options:
1. Put the version in the http response header
2. Put the version in the http response body
3. Have a separate endpoint for querying version

Could we/would we want to support version negotiation?

**Comment by carlwilson** [comment]
This one's important for 1.3 IMO, I'd vote for the HTTP header implementation, it's simple and in every response automagically. A "cheap" HEAD request will get you the info you want then.

**Comment by carlwilson** [comment]
API HEADER definition: Closed by #75

See openpreserve/par-wikidp#1
