### ISSUE TITLE
PAR Schema is not semantically documented in version control

### ISSUE THREAD

**Issue by jackdos** [openpreserve/par#22]
As a potential user or implementer of the PAR schema and API, I want to understand the entities in the schema in high level terms of what they represent, how they are intended to be used and how they are inter-related. I want this information available in a version controlled manner so that I can be confident that they describe the version of the schema and API I am actually operating with.

**Comment by jhsimpson** [comment]
related to #8 

We want v1.2.0 to include a way for implementations to report the version of the par spec they support.
