### ISSUE TITLE
Is schema the right choice of sub-dir?

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/par#57]
Given that the `schema` dir provides the model for the API YAML definition perhaps this should be moved below the `api` sub-dir and/or me renamed to `model` to be more specific?

**Comment by jhsimpson** [comment]
I disagree.  I think the json schemas should be usable without using the api specification.

**Comment by carlwilson** [comment]
I'm inclined to agree as do the published URLs so closing this.
