### ISSUE TITLE
Publish API doc 

### ISSUE THREAD

**Issue by MartinSpeller** [openpreserve/par#9]
Need to publish the API Swagger doc.

Create link to swagger doc and include in Github pages under resources

**Comment by jhsimpson** [comment]
#8 we want to use OpenAPI3, instead of Swagger, starting in v1.2.0.  Once #8 is closed, we can confirm that the api spec has a publicly reachable url.

**Comment by jackdos** [comment]
Looks like a good idea to me

**Comment by jhsimpson** [comment]
parcore.org uses github pages right @carlwilson ?  It is possible to host the swagger ui in github pages, which I think would be better.
https://medium.com/@crshnburn/embed-swagger-ui-in-github-pages-9c77a86b2fd2

**Comment by carlwilson** [comment]
Will discuss in the call, today.
